all: sparse_matrix_transpose.c sparse_matrix_multiply.c function.c
	gcc -o sparse_matrix_transpose sparse_matrix_transpose.c function.c
	gcc -o sparse_matrix_multiply sparse_matrix_multiply.c function.c
clear:
	rm sparse_matrix_transpose
	rm sparse_matrix_multiply